
# Base URL
baseurl: http://coolnuanfeng.github.io

# Site live URL
#url: http://coolnuanfeng.github.io

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 个人博客
  # Little description about your site
  description: A web front-end programmer's personal blog.
  meta_description: '吴虹松的个人博客'
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: wuhongsong
    email:  coolnuanfeng@gmail.com
    url: http://coolnuanfeng.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Profile links, leave blank to ignore
  social: 
    github: coolnuanfeng
    twitter: coolnuanfeng
    facebook: coolnuanfeng
    gplus: +coolnuanfeng
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  #show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
